### ISSUE TITLE
Open Eclipse with tool installed

### ISSUE THREAD

**Issue by chbrown13** [DeveloperLiberationFront/Program-Navigation-Plugin#122]
Don't use a runtime workspace, so the user has to start Eclipse twice. Instead, have the plugins deployed in the base Eclipse. It's generally a pretty easy operation: http://stackoverflow.com/questions/266935/deploying-a-newly-developed-eclipse-plugin

**Comment by chbrown13** [comment]
Running into issues exporting because of org.eclipse.jdt.ui package

**Comment by CaptainEmerson** [comment]
Makes sense. I wonder if you can just swap in the appropriate class files manually. I assume there are few of them.

**Comment by chbrown13** [comment]
No luck with switching out the class files, it's causing some other errors now.

**Comment by CaptainEmerson** [comment]
Are the classes you're swapping exactly the same as the version (modulo your changes?) Try compiling the original version of the class you're swapping, then swapping that class file in to the deployed Eclipse. That *should* work, unless there's some sort of security issue. If that works, then make a minor change, and see if you can swap that in.

**Comment by jssmith1** [comment]
Alternatively, it might also be worth exploring whether we could snapshot the VM with the tool already running in Eclipse. I'm not sure what the limitations are of creating snapshots while an application is running, but it would certainly eliminate the time required to start Eclipse and launch the tool.

**Comment by chbrown13** [comment]
Tool is mostly working in the VM now except for a few issues.
