### ISSUE TITLE
Update VM on website

### ISSUE THREAD

**Issue by jssmith1** [DeveloperLiberationFront/Program-Navigation-Plugin#125]
Put the VM containing the latest and greatest version of the tool online!

**Comment by jssmith1** [comment]
@chbrown13 I'm a little unclear on what the status of the VM is right now. Seems like you are still working on #128 and #129. Any estimate on when we'll have a VM to upload?

**Comment by chbrown13** [comment]
@jssmith1

**Comment by chbrown13** [comment]
Not sure exactly but hopefully in a few hours. Are these two issues a priority to get done?

**Comment by jssmith1** [comment]
Technically we should have a stable version of the VM done by the submission deadline tonight. If there are any minor issues remaining, we should update the readme to get out ahead of them.

**Comment by chbrown13** [comment]
Ok, it pretty much works fine when you open Eclipse and use it on the first time. After you start the tool there's no way to turn it off and then if you close and re-open Eclipse the breadcrumbs are still enabled and then disabling/enabling them is causing issues with the display.

**Comment by jssmith1** [comment]
Ok. I guess just upload an updated version of the VM to gDrive by 11:00 tonight and make the necessary adjustments to the getting started guide. Let me know once you do so I can update the link on my webpage. If you think the issues can be resolved with one or two more days work, see what you can do. We might be able to provide a newer VM when they make the formal request.

**Comment by chbrown13** [comment]
@jssmith1 Uploading the new VM now. Also I made some updates to the paper to fix some typos and stuff in the text.

**Comment by jssmith1** [comment]
Awesome! And good catches in 5562e6b5e2949294ca37c49b5e5b5c398f015517

**Comment by chbrown13** [comment]
Finally finished uploading, here's the link: https://drive.google.com/open?id=0B384dHeXAHG5enlnU21TZDdwVWs

**Comment by jssmith1** [comment]
@chbrown13: I'm getting the following error when I try to follow the getting started guide with the out-of-the-box VM

![image](https://cloud.githubusercontent.com/assets/5032534/16538300/4effadfc-3fee-11e6-9fff-3a12cfc2c5c3.png)

I made sure I was in the right workspace and in the correct perspective.

**Comment by chbrown13** [comment]
Switch the workspace to /home/flower/Desktop/Flower.

**Comment by chbrown13** [comment]
Actually I'm seeing that too now for some reason, taking a look.

**Comment by chbrown13** [comment]
I think opening Eclipse on startup is doing something here with the files. It works fine on startup after the first time or two but eventually it always goes to this error. The temporary fix is to re-import the project but haven't found a permanent one yet.

**Comment by jssmith1** [comment]
Also getting this error whenever I import the VM:

> The import failed because flower.ova did not pass OVF specification conformance or virtual hardware compliance checks.

However, it doesn't seem to be an issue after I hit retry.

**Comment by chbrown13** [comment]
I've never seen that error.
