### ISSUE TITLE
Check conventions

### ISSUE THREAD

**Issue by jssmith1** [DeveloperLiberationFront/Program-Navigation-Plugin#137]
- \textsc{Design principles}
- \textttt{Code}
- \textit{Tools}
    -Should Flower be texit?

**Comment by jssmith1** [comment]
@chbrown13: Could you double check that these are consistent throughout the paper?

**Comment by jssmith1** [comment]
Whoops, just now pushed the fix that actually implements these conventions:

bc2fc9a61f4b0131acbfeb38bb5f8b7ff46fc87d

**Comment by chbrown13** [comment]
I'm fine with \textit for Flower
