### ISSUE TITLE
More details about stats tests

### ISSUE THREAD

**Issue by jssmith1** [DeveloperLiberationFront/Program-Navigation-Plugin#147]
Regarding the evaluation, can you give more details any hypothesis tested and the appropriateness of the tests applied – e.g. relating to the variance of the samples?

**Comment by jssmith1** [comment]
R3 requests clarification about the statistical tests we applied. We tested whether participants performed differently — in terms of task completion time and correctness — using the full suite of Eclipse tools, compared with Flower. We first tested the distribution task completion times for normality using the Shapiro-Wilk test and failed to reject the null hypothesis (p=.21 and p=.43 for each task, respectively). Therefore, we tested for differences in task completion time by performing two-tailed, unpaired, two-sample t-tests. We tested for differences in task correctness using a chi square test, which is appropriate for nominal data.

**Comment by jssmith1** [comment]
Not sure how much of this to include given space limitations...

**Comment by CaptainEmerson** [comment]
SGTM
