### ISSUE TITLE
Data Flow Links

### ISSUE THREAD

**Issue by chbrown13** [DeveloperLiberationFront/Program-Navigation-Plugin#15]
Add ability for users to click the links in the text box and open the new file.

**Comment by chbrown13** [comment]
Power's been out at my apartment all weekend so haven't really been able to work on this.

**Comment by CaptainEmerson** [comment]
Not a problem! A random suggestion on workflow, though. I can see from the issues that you're working on these issues regularly, but perhaps you could include either some screenshots of some paper sketches of what you expect the UI to look like? It's pretty easy in GH -- you can just copy/paste images.

For instance, in this issues, a little sketch of what you're trying to do (pointing out the relevant parts of the UI) would help me visualize what you're planning here. The sketch doesn't need to be a big production or anything -- maybe just a picture of a paper sketch from your phone.

**Comment by chbrown13** [comment]
Sure, no problem.

**Comment by chbrown13** [comment]
Current pop-up box

![image](https://cloud.githubusercontent.com/assets/4522684/12537862/56b152fe-c298-11e5-95b6-3790fe5b04d4.png)

**Comment by chbrown13** [comment]
When the user clicks on the link in the pop-up box, we want the Eclipse editor to open the location where that method is declared (down) or used (up). In the example above- the Date parameter _d_ is passed into a function called _recent_, and recent is called by another function _getMessageAsSentence_. When the user clicks on the _getMessageAsSentence_ link, we want to open where _recent_ is called inside of _getMessageAsSentence_.

**Comment by CaptainEmerson** [comment]
Since it's clunky looking, remove the shell trim (http://www.java2s.com/Tutorial/Java/0280__SWT/ShellwithoutTitlebar.htm). My pie menu implementation in my refactoring tools is a good example of how to do it.

**Comment by chbrown13** [comment]
Ok, thanks

**Comment by chbrown13** [comment]
Error message for clicked links for method outside of the current project.

![image](https://cloud.githubusercontent.com/assets/4522684/13030417/5daa53fe-d278-11e5-9480-2df7f397c7d8.png)
