### ISSUE TITLE
Plugin Menu Option

### ISSUE THREAD

**Issue by chbrown13** [DeveloperLiberationFront/Program-Navigation-Plugin#16]
Use a menu that allows users to switch between up and down search rather than radio buttons.

**Comment by chbrown13** [comment]
Button in menu bar to start plugin tool:
![image](https://cloud.githubusercontent.com/assets/4522684/12537907/9f1ec76e-c299-11e5-9366-c3efe2a4dc4e.png)

Pop-up box:
![image](https://cloud.githubusercontent.com/assets/4522684/12537919/c4d4dc14-c299-11e5-84b6-8aa9d67ba838.png)

**Comment by chbrown13** [comment]
Rather than having the radio buttons on the actual pop-up box, @jssmith1 suggested adding a drop-down menu option in Eclipse to switch between up and down:
blob:https%3A//mail.google.com/e8b21a57-0955-446d-b893-37151d5c88b1

**Comment by chbrown13** [comment]
That means the pop-up box would only have links to the navigation and would look something like this: 
![image](https://cloud.githubusercontent.com/assets/4522684/12538009/8a1d7e12-c29b-11e5-9d41-b1e33dd7e1cb.png)

Should this contain any more information (i.e. class name, path, etc.)?

**Comment by CaptainEmerson** [comment]
Where does the drop down go? On the Eclipse toolbar? It's quite a ways to move the mouse, plus it requires two clicks rather than one to move between the options.

After scrum on Monday, let's talk about the down/up widgets.

**Comment by chbrown13** [comment]
Yes, it would moved to the toolbar.

**Comment by chbrown13** [comment]
Also FYI Justin and I both have class at 1:30 after scrum.

**Comment by chbrown13** [comment]
No longer using menu
