### ISSUE TITLE
Tool highlights everything with the same name

### ISSUE THREAD

**Issue by chbrown13** [DeveloperLiberationFront/Program-Navigation-Plugin#18]
Should only highlight the variables in the method

**Comment by chbrown13** [comment]
Finder map uses string as key and highlights everything with that value.

**Comment by jssmith1** [comment]
We ran into an issue with highlighting the list object, queries in our testing today.

**Comment by tralber2** [comment]
Resolved highlighting objects. 
![objecthighlight](https://cloud.githubusercontent.com/assets/16580090/13240783/6839cf2e-d9b3-11e5-83e0-2bb337979840.PNG)

**Comment by jssmith1** [comment]
Looks good. Let's test it on the study task today.
