### ISSUE TITLE
Hyperlinks in code

### ISSUE THREAD

**Issue by jssmith1** [DeveloperLiberationFront/Program-Navigation-Plugin#19]
* When highlighting a parameter in the method declaration click the method name to navigate up (when there is only 1 caller of the method)

* When highlighting a parameter in a method call, click the method name to navigate down to the method declaration

**Comment by CaptainEmerson** [comment]
To the first bullet, when there are multiple callers, just pick one (deterministically) to navigate to.

To the second bullet, "the method declaration" could actually be multiple method declarations. As with the first bullet, pick one deterministically.

**Comment by chbrown13** [comment]
How do we want these to be displayed? Similar to how the tool was before with the shells right above the cursor.

**Comment by jssmith1** [comment]
Could the method name get turned into a hyperlink?

**Comment by chbrown13** [comment]
Possibly, not sure

**Comment by CaptainEmerson** [comment]
Yep, no shells -- just turn the text into a hyperlink.
