### ISSUE TITLE
Add off-screen highlights to their respective boxes

### ISSUE THREAD

**Issue by jssmith1** [DeveloperLiberationFront/Program-Navigation-Plugin#20]

**Comment by chbrown13** [comment]
For class variables, how should the links be displayed to go to instances in the same class but not in the view of the screen in the navigation boxes?

**Comment by chbrown13** [comment]
Just display the line #?

**Comment by CaptainEmerson** [comment]
The top and bottom boxes should indicate the direction and horizontal position of the references above and below the current visible scroll region.

**Comment by chbrown13** [comment]
Pretty much done but some dependencies on Tyler's work to capture all instances in #18

**Comment by chbrown13** [comment]
![image](https://cloud.githubusercontent.com/assets/4522684/13066985/85213a7a-d439-11e5-9354-1361abce6036.png)
