### ISSUE TITLE
Tool's Name

### ISSUE THREAD

**Issue by jssmith1** [DeveloperLiberationFront/Program-Navigation-Plugin#22]
We should come up with a cool name for our tool. Any ideas?

**Comment by chbrown13** [comment]
@jssmith1 @tylerrexford Do we need to meet to go over the project proposal for class tomorrow?

**Comment by tylerrexford** [comment]
We could like 10 minutes before.

**Comment by chbrown13** [comment]
Ok, that works. And don't really have any name ideas- Program Navigation Plugin?

**Comment by tylerrexford** [comment]
Are we still meeting early? If so where

**Comment by chbrown13** [comment]
EB1 lobby?

**Comment by jssmith1** [comment]
I'll be there right after scrum.

-Justin

**Comment by tylerrexford** [comment]
I'm here

**Comment by tylerrexford** [comment]
1. The default PNP-program navigation plugin. simple and to the point

**Comment by jssmith1** [comment]
ProNav, ProgNav, NavPro, or some variation on Program and Navigation
ProgFlowRida

**Comment by chbrown13** [comment]
DataTracker

**Comment by jssmith1** [comment]
Flower (pronounced like data flow)
