### ISSUE TITLE
Push full project to Github

### ISSUE THREAD

**Issue by chbrown13** [DeveloperLiberationFront/Program-Navigation-Plugin#28]
The plug-in depends on the org.eclipse.jdt.ui package that I modified locally for fixing the UI but haven't been able to find a way to push everything to Github.

**Comment by chbrown13** [comment]
Added modified packages org.eclipse.jdt.internal.ui.javaeditor and org.eclipse.jdt.internal.ui.javaeditor.breadcrumb as .jar files. Whenever you get the chance can you try pulling this version and seeing if the compiler errors are gone and if you can run the tool? @tylerrexford @jssmith1

**Comment by jssmith1** [comment]
@chbrown13 
Pulled the changes and rebuilt the project, but still getting errors:

Breadcrumb undefined for type Java editor and setText undefined for the type IBreadcrumb.

![image](https://cloud.githubusercontent.com/assets/5032534/13375798/8def61e4-dd77-11e5-960b-4f6c1ef6ad80.png)

**Comment by tralber2** [comment]
I think to fix this, you have to move the modified jar above the plugin dependencies. I did that and do not have compiler errors anymore. Although I ran the plugin and was getting null pointer exceptions from the breadcrumb. It was a very small program and probably had to do with not having any chains of invocation or declaration. 
![issue28fix](https://cloud.githubusercontent.com/assets/16580090/13400046/f484fd4e-ded3-11e5-84ee-2688c4800113.PNG)

**Comment by jssmith1** [comment]
Yup, moving it up in the build path works
