### ISSUE TITLE
Determine which AST class to search for

### ISSUE THREAD

**Issue by jssmith1** [DeveloperLiberationFront/Program-Navigation-Plugin#3]
Once we complete #2, we need to determine which [AST Class(es)](https://www.eclipse.org/articles/article.php?file=Article-JavaCodeManipulation_AST/index.html) correspond with the program elements we want to highlight.

**Comment by chbrown13** [comment]
http://grepcode.com/file/repository.grepcode.com/java/eclipse.org/4.3/org.eclipse.jdt/core/3.9.0/org/eclipse/jdt/core/dom/ASTNode.java#ASTNode

**Comment by chbrown13** [comment]
SimpleName
