### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by jssmith1** [DeveloperLiberationFront/Program-Navigation-Plugin#34]
We need a nice (high-resolution) screenshot of the tool for the paper. Preferably a vector image, but that might be impossible to get from eclipse.

We'll want to do want to do something like figure 1 here except the letters should be on top of as screenshot not a mockup: http://people.engr.ncsu.edu/ermurph3/papers/icse-nier-15.pdf

**Comment by chbrown13** [comment]
Turn off true type

**Comment by jssmith1** [comment]
Also see Fig 1 from this short paper at VL/HCC 2015 http://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=7357211

**Comment by chbrown13** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/4522684/13693030/9e524d2a-e714-11e5-9325-1ec995ac8c2e.png)

**Comment by chbrown13** [comment]
Sample screenshot to use. Is there a good way to add the letter overlays to an image to keep it high resolution?

**Comment by jssmith1** [comment]
I think any image editing software should be fine. I've used paint/powerpoint, but that might not be the best option. Try asking in Slack. Also see if you can simplify the screenshot. You should be able to remove some of the white space to the right and some of the methods/constructors that aren't relevant (e.g. SQLFileCache, the hash map, ...). Maybe add a comment that contains the string "fileName" so we can talk about how the tool only highlights proper references in the code.

**Comment by CaptainEmerson** [comment]
If you want to "write" on top of a screenshot, I would turn it into a PDF and use Inkscape to add text.

Other suggestions:
* The figure does look non-lossy, so that's good, but it still looks like font smoothing (cleartype) is on.
* There's a lot of wasted space on the right side of the figure. At minimum, you can reduce the horizontal size of the editor. You could probably hard wrap the throws part of the signatures, and right hand side of "cache"

**Comment by chbrown13** [comment]
Ok cool, was trying to use Paint but wasn't working too well. Will update the screenshot and try out Inkscape.

**Comment by chbrown13** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/4522684/13712999/b43d5dca-e794-11e5-94b5-bd1d7ea23420.png)

**Comment by chbrown13** [comment]
Updated screenshot

**Comment by CaptainEmerson** [comment]
So somewhere there the most recent screenshot got lossy -- zoom in and you can see it.

**Comment by chbrown13** [comment]
Ok, played around with the cleartype settings and might have messed something up.

**Comment by chbrown13** [comment]
![plugin](https://cloud.githubusercontent.com/assets/4522684/13713862/244c9384-e799-11e5-83bd-1518278fe425.png)

**Comment by CaptainEmerson** [comment]
Further suggestions:
* Still some horizontal waste than can be trimmed, including whitespace on the left and right
* I'd show more of the editor -- at least the tab, and probably the right hand scrollbar.
* I feel like lines 42 and afterwards don't buy you anything. I'd like to see something more sophisticated happening in the UI for method calls that are already on screen, but not for this submission.
* Javadoc seems a bit long -- may want to cut it if you need space

**Comment by chbrown13** [comment]
![image4144](https://cloud.githubusercontent.com/assets/4522684/13723712/13ac5814-e83b-11e5-8cf0-083601d9dc4b.png)

**Comment by chbrown13** [comment]
![screenshot5](https://cloud.githubusercontent.com/assets/4522684/13723893/f16ac500-e840-11e5-8034-28f8fad44f6e.png)

**Comment by chbrown13** [comment]
![screenshot6](https://cloud.githubusercontent.com/assets/4522684/13751126/0cc3a1e2-e9df-11e5-8f2e-4aa756237b34.png)

**Comment by jssmith1** [comment]
![toolscreenshot](https://cloud.githubusercontent.com/assets/5032534/13864250/564a9520-ec76-11e5-8cd4-22b61b7c8355.png)

Some comments on the figure:
- We don't mention the C's in the paper. We should probably just remove them.
- Shouldn't the fileName on line 31 be selected in the second screenshot?
- We don't refer to the second figure in the text at all, so we could probably remove all the letters.

**Comment by CaptainEmerson** [comment]
Also
- [ ] The "Click B2" arrow would be better if if it weren't overlapping with text
- [ ] The cursor on the right should be on line 32, in filename, right? If so, shouldn't that variable ref be the darkest blue?

**Comment by chbrown13** [comment]
Updated screenshot image
![toolscreenshot](https://cloud.githubusercontent.com/assets/4522684/13867464/7465da64-ec95-11e5-86e8-5764cd7fcae1.png)
