### ISSUE TITLE
Participant Table

### ISSUE THREAD

**Issue by jssmith1** [DeveloperLiberationFront/Program-Navigation-Plugin#35]
Once we're done with #33  we need to add a single column latex table to the paper. Something like:

Participant # | Years of Experience | Previous use of Eclipse

**Comment by chbrown13** [comment]
Does the table need to be in any specific format?

**Comment by jssmith1** [comment]
Check out what I did here to get started - https://github.com/DeveloperLiberationFront/iTrustInterviews/blob/master/iTrustInterviews.tex

**Comment by jssmith1** [comment]
'\begin{table}
\centering
\caption{Participant Demographics}
\begin{tabular}{|l|l|c|S|}
\rowcolor{gray!50}
\hline
    Participant		& Job Title 						& Vulnerability 			&\multicolumn{1}{c|}{Experience} \\
    \rowcolor{gray!50}
    				&									& Familiarity				&   \multicolumn{1}{c|}{Years} \\
    \hline
    P1*			    & Student     						& \CIRCLE{}\CIRCLE{}\LEFTcircle{}\Circle{}\Circle{} 	&  4.5    \\
    \hline
    P2*			    & Test Engineer    					& \CIRCLE{}\CIRCLE{}\CIRCLE{}\Circle{}\Circle{}		&  8 		\\
    \hline
    P3 				& Development Tester       			& \CIRCLE{}\CIRCLE{}\Circle{}\Circle{}\Circle{}		&  6 	    	\\
    \hline
    P4*				& Software Developer     			& \CIRCLE{}\CIRCLE{}\Circle{}\Circle{}\Circle{}			&  6     	\\
    \hline
    P5*				& Student      						& \CIRCLE{}\CIRCLE{}\CIRCLE{}\CIRCLE{}\Circle{}			&  10 	\\
    \hline
    P6				& Student		    				& \CIRCLE{}\Circle{}\Circle{}\Circle{}\Circle{}			& 4		\\
    \hline
    P7				& Software Developer    	& \CIRCLE{}\CIRCLE{}\CIRCLE{}\CIRCLE{}\Circle{}		& 4.5         \\
    \hline
    P8				& Student	    					& \CIRCLE{}\CIRCLE{}\CIRCLE{}\Circle{}\Circle{}		& 7   \\
    \hline
    P9				& Software Consultant   	 		& \CIRCLE{}\CIRCLE{}\CIRCLE{}\Circle{}\Circle{}		& 5	  		 \\
    \hline
    P10			    & Student    						& \CIRCLE{}\CIRCLE{}\CIRCLE{}\Circle{}\Circle{}		& 8	           \\
    \hline
\end{tabular}
\label{table:participants}
\end{table}'

**Comment by chbrown13** [comment]
'\begin{table}
\centering
\caption{Participant Demographics}
\begin{tabular}{|l|l|c|S|}
\rowcolor{gray!50}
\hline
Participant & Professional Experience & Java Experience & Previous Use of Eclipse\
\rowcolor{gray!50}
\hline
P1 & 9 & 5 & Yes \
\hline
P2 & 0 & 6 & Yes \
\hline
P3 & 3 & 2 & No \
\hline
P4 & 5 & 0 & No \
\hline
P5 & 12 & 10 & Yes \
\hline
P6 & 0 & 3.5 & Yes \
\hline
P7 & 1 & 9 & Yes \
\hline
P8 & 5.5 & 1.5 & Yes \
\hline
\end{tabular}
\label{table:participants}
\end{table}'

**Comment by jssmith1** [comment]
@chbrown13: Go ahead and add the table into the .tex document

**Comment by chbrown13** [comment]
Added the table to the progNav Paper.tex but I'm not able to open the paper and view it. Are all of the necessary files here? I'm getting 

LaTeX Error: File `cite.sty' not found.

**Comment by jssmith1** [comment]
Hmm. Sounds like your version of Tex isn't downloading dependencies correctly. That file isn't something that's typically in the repository. What editor do you use?

**Comment by barik** [comment]
If it's Windows, you'll probably want to be using [MikTeX](http://miktex.org/). Then, make sure that you have Installing missing packages on-the-fly set to `Yes`.

![2016-03-10_23-00-28](https://cloud.githubusercontent.com/assets/441243/13692961/ef1d05b6-e713-11e5-989f-1bb90a8090f0.png)

**Comment by chbrown13** [comment]
Ok, I'm using TeXworks

**Comment by jssmith1** [comment]
@chbrown13 Did that recommendation work?

**Comment by chbrown13** [comment]
No luck so far.
