### ISSUE TITLE
Table for task times and correctness

### ISSUE THREAD

**Issue by jssmith1** [DeveloperLiberationFront/Program-Navigation-Plugin#37]
Or maybe a couple bar graphs. See attached from Latoza's reacher
![image](https://cloud.githubusercontent.com/assets/5032534/13731747/f08ca50c-e946-11e5-8c57-4dda932b985a.png)

**Comment by chbrown13** [comment]
![image](https://cloud.githubusercontent.com/assets/4522684/13751861/858fa5c8-e9e2-11e5-8ae4-9419199e51a5.png)

**Comment by chbrown13** [comment]
![image](https://cloud.githubusercontent.com/assets/4522684/13752142/b7109f2a-e9e3-11e5-8f4b-800b2640b3e1.png)

**Comment by jssmith1** [comment]
Some thoughts:

- I think I associate a more blue color with our tool, since the highlights and links it creates are all blue. 
- The first figure takes up a little too much horizontal space
- Tool/no tool aren't the most accurate labels. How bout "Our Tool's Name"/Eclipse Tools
- What were the raw numbers for the second graph? I think it would be better to report them in the text rather than graphically

**Comment by chbrown13** [comment]
Average Time to First Call Location for Task 1: Our tool = 7.75, Eclipse tools = 43.75 seconds

**Comment by jssmith1** [comment]
@chbrown13: What were the numbers for average task time? Do they account for P8's weirdness?

**Comment by chbrown13** [comment]
After accounting for P8:
* Task 1 with tool = 275.75
* Task 1 without tool = 401.5
* Task 2 with tool = 385
* Task 2 without tool = 250.5
