### ISSUE TITLE
Update code to highlight variables instead of statements

### ISSUE THREAD

**Issue by jssmith1** [DeveloperLiberationFront/Program-Navigation-Plugin#4]

**Comment by chbrown13** [comment]
Got SimpleName to highlight all identifiers (variables, method names, classes, etc.). Modify to only allow variables: http://grepcode.com/file/repository.grepcode.com/java/eclipse.org/4.3.1/org.eclipse.jdt/core/3.9.1/org/eclipse/jdt/core/dom/SimpleName.java#SimpleName

**Comment by chbrown13** [comment]
Can't extend SimpleName outside of package

**Comment by chbrown13** [comment]
Local version works for declared variables and parameters. How should we handle for and while loops @jssmith1?

**Comment by chbrown13** [comment]
Done

**Comment by CaptainEmerson** [comment]
@chbrown13 : it'd be helpful to me if, when you commit, you could mention the issue, so the code and the issue get linked together. It'll help add some transparency.

**Comment by chbrown13** [comment]
Ok
