### ISSUE TITLE
Background Section

### ISSUE THREAD

**Issue by jssmith1** [DeveloperLiberationFront/Program-Navigation-Plugin#40]
Should probably contain 3 subsections (Production Tools ie what's in eclipse/intellij, Visualization tools, IDE integrated tools), each with one paragraph.

Each paragraph should describe what the tools/work are in that category and conclude with how our tool is different.

**Comment by chbrown13** [comment]
What's the difference between productions tools and IDE integrated tools?

**Comment by jssmith1** [comment]
IDE integrated tools could include research tools that work primarily in the code view. There might be a better way to split up the related work. Once it's written it shouldn't be hard to shuffle things around.

**Comment by chbrown13** [comment]
Also I'm not able to add any of the citations because I'm still getting that cite.sty error.

**Comment by jssmith1** [comment]
@chbrown13: You could create a blank project on ShareLaTex: https://www.sharelatex.com?r=c4aba112&rm=d&rs=b

One of us has to have premium to actually collaborate on there, but you could copy and paste your changes into a project on there to test the build

**Comment by barik** [comment]
@jssmith1: I have a premium account if you would like me to create one for you to use.

**Comment by jssmith1** [comment]
Thanks @barik! That would be awesome. I can just import the paper from [github](https://github.com/DeveloperLiberationFront/Program-Navigation-Plugin/tree/master/progNav%20Paper), right?

**Comment by barik** [comment]
@jssmith1 That's more tricky. It might try to sync with my GitHub account. I created a project for you. Try it and see.

**Comment by jssmith1** [comment]
Thanks!
