### ISSUE TITLE
Upload study materials to my website

### ISSUE THREAD

**Issue by jssmith1** [DeveloperLiberationFront/Program-Navigation-Plugin#41]

**Comment by jssmith1** [comment]
- [ ] Create stub for submission link
- [ ] include a video #59 
- [ ] add vm image #59
- [ ] add study materials

**Comment by chbrown13** [comment]
https://drive.google.com/open?id=0B384dHeXAHG5MmJaUnNZSlBRTEU

**Comment by chbrown13** [comment]
https://drive.google.com/open?id=0B384dHeXAHG5OE55R0syclp6blE
