### ISSUE TITLE
online, I think it'd be good to have a video of...

### ISSUE THREAD

**Issue by jssmith1** [DeveloperLiberationFront/Program-Navigation-Plugin#59]
![snippet](https://lh3.googleusercontent.com/-6soTCb7Vrio/VuikQEkzjPI/AAAAAAAADjQ/8D3sIlcPhlY/s800/%25255BUNSET%25255D.png)

online, I think it'd be good to have a video of the tool and a the tool in a small linux VM.

**Comment by jssmith1** [comment]
@tylerrexford, could you look into getting a version of our tool installed in a linux vm?

**Comment by tylerrexford** [comment]
Um, I can try. Where do I start with that? As in, do you want me to load it
onto the eos system or what?

**Comment by jssmith1** [comment]
We want people to be able to take a virtual machine image that we make available, launch that vm image and run our tool without any setup or installation. I'm not too familiar with the process of creating vm images, but @CaptainEmerson had students do this as part of the grad software engineering project. Perhaps he could advise.

**Comment by tylerrexford** [comment]
Yeah that would be pretty solid. If he doesn't respond tonight I'll shoot him an email and see if he can help. I'm sure it's a relatively easy setup if you know what you're doing.

**Comment by chbrown13** [comment]
I was in that class so I can look into it.

**Comment by chbrown13** [comment]
Do care what operating system the tool is on for the VM?

**Comment by jssmith1** [comment]
Don't think so

**Comment by CaptainEmerson** [comment]
Not windows

**Comment by chbrown13** [comment]
Are we going to want anything else on the VM other than the tool and a README with some stuff in it?
