### ISSUE TITLE
seems odd to put here, not in last paragraph. i...

### ISSUE THREAD

**Issue by jssmith1** [DeveloperLiberationFront/Program-Navigation-Plugin#62]
![snippet](https://lh3.googleusercontent.com/-qPrK13mUJN8/VuikQjRIasI/AAAAAAAADjc/fJ7GYhpAnfI/s800/%25255BUNSET%25255D.png)

seems odd to put here, not in last paragraph. in Table II, maybe say who was in each group?

**Comment by chbrown13** [comment]
Added to Participant Table

**Comment by jssmith1** [comment]
The group numbers on their own probably won't mean much to the reader. We probably need some text or a different way of denoting groups to describe what each group number means.

**Comment by chbrown13** [comment]
Updated the table @jssmith1
