### ISSUE TITLE
Issue Pulling from Github 

### ISSUE THREAD

**Issue by chbrown13** [DeveloperLiberationFront/Program-Navigation-Plugin#7]
For some reason it was running fine in my local area but after recently pushing and then re-pulling the latest version in Eclipse now the plugin isn't working correctly and I get an error "The chosen operation is not currently available". Has anyone else seen this issue or any ideas @jssmith1 @CaptainEmerson?

**Comment by CaptainEmerson** [comment]
That's kinda the catch-all error in Eclipse. I'd probably roll back to prior versions until you find one that works, then figure out the difference between the two versions.

**Comment by chbrown13** [comment]
Ok, I'll check it out.

**Comment by chbrown13** [comment]
Should be working now
