### ISSUE TITLE
vectorize figure. errant grey line at left

### ISSUE THREAD

**Issue by jssmith1** [DeveloperLiberationFront/Program-Navigation-Plugin#72]
![snippet](https://lh3.googleusercontent.com/-Q5ADGFUQOrQ/VuikSuJp5nI/AAAAAAAADkE/6GImgFWkzOc/s800/%25255BUNSET%25255D.png)

vectorize figure. errant grey line at left

**Comment by jssmith1** [comment]
@chbrown13: Could you tackle this issue? The image still has a popup and a grey bar at the top. 
![image](https://cloud.githubusercontent.com/assets/5032534/13799984/dc904b0c-eafa-11e5-9df0-602412116034.png)

It should be possible to export the excel chart to pdf to vectorize it

**Comment by chbrown13** [comment]
Sure

**Comment by jssmith1** [comment]
The image is still in png format. Is it possible to export it from excel as a pdf?

**Comment by chbrown13** [comment]
@jssmith1 Should be pdf now
